services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: product_service_user
      MONGO_INITDB_ROOT_PASSWORD: product_service_password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db
